FROM node:22-alpine AS base
WORKDIR /home/node/app

COPY package*.json ./

RUN npm ci --prefer-offline --progress=false --no-audit

COPY . .

FROM base AS setup
RUN node --run setup

FROM base AS seeds-run
RUN node --run seeds:run