FROM hub.agcs.agetic.gob.bo/dockerhub-proxy/library/node:22-alpine AS deps
WORKDIR /home/node/app

COPY package*.json ./

RUN npm set registry https://registry.agcs.agetic.gob.bo/ && \
    npm set strict-ssl false && \
    npm ci --prefer-offline --progress=false --no-audit

COPY . .

RUN node --run build

FROM deps AS merge
RUN node --run format-check
