export enum RolEnum {
  USUARIO = 'USUARIO',
  ADMINISTRADOR = 'ADMINISTRADOR',
  INVESTIGADOR = 'INVESTIGADOR',
  OPERATIVO = 'OPERATIVO',
  SEGUIMIENTO_JURIDICO = 'SEGUIMIENTO_JURIDICO',
  SEGUIMIENTO_CASOS = 'SEGUIMIENTO_CASOS',
  INVESTIGADOR_FINANCIERO = 'INVESTIGADOR_FINANCIERO',
  INTELIGENCIA = 'INTELIGENCIA',
  TODOS = '*',
}
