export * from './create-operativo.dto'
export * from './create-droga.dto'
export * from './create-detenido.dto'
export * from './create-bien-secuestrado.dto'
export * from './create-fabrica.dto'
export * from './create-sustancia.dto'
export * from './create-galeria.dto'
export * from './create-logotipo.dto'
