FROM node:22-alpine AS build
WORKDIR /home/node/app

COPY package*.json ./

RUN npm ci --prefer-offline --progress=false --no-audit

COPY . .

RUN node --run build

FROM node:22-alpine AS prod-deps
WORKDIR /home/node/app
COPY package*.json ./
RUN npm ci --omit=dev --prefer-offline --progress=false --no-audit

FROM node:22-alpine AS release
WORKDIR /home/node/app
RUN chown -R node:node /home/node/app

COPY --from=prod-deps --chown=node:node /home/node/app/node_modules ./node_modules
COPY --from=build --chown=node:node /home/node/app/dist ./dist

ARG CI_COMMIT_SHORT_SHA
ARG CI_COMMIT_MESSAGE
ARG CI_COMMIT_REF_NAME
ENV CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA} \
    CI_COMMIT_MESSAGE=${CI_COMMIT_MESSAGE} \
    CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME}

FROM release AS app
USER node
CMD ["sh", "-c", "node dist/src/main"]
EXPOSE 3000
