export * from './create-blanco.dto'
export * from './create-antecedente.dto'
export * from './create-red-social.dto'
export * from './create-lugar-sig.dto'
export * from './create-archivo.dto'
export * from './create-flujo-telefonico.dto'
export * from './create-flujo-fiscalia.dto'
