export enum MetodoAutenticacion {
  LOCAL = 'LOCAL',
  CIUDADANIA_DIGITAL = 'CIUDADANIA_DIGITAL',
  KEYCLOAK = 'KEYCLOAK',
  DOS_FA = '2FA',
}

export enum AccionAuditoria {
  INSERT = 'INSERT',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
}

export enum MotivoFalloLogin {
  CREDENCIALES_INVALIDAS = 'CREDENCIALES_INVALIDAS',
  CUENTA_BLOQUEADA = 'CUENTA_BLOQUEADA',
  CUENTA_INACTIVA = 'CUENTA_INACTIVA',
  CUENTA_PENDIENTE = 'CUENTA_PENDIENTE',
  CODIGO_2FA_INVALIDO = 'CODIGO_2FA_INVALIDO',
  TOKEN_EXPIRADO = 'TOKEN_EXPIRADO',
}
