# ----------- BUILD -----------
FROM node:22-alpine AS build
WORKDIR /home/node/app

COPY package*.json ./

# ❌ quitado registry AGETIC
RUN npm ci --progress=false --no-audit --ignore-scripts --legacy-peer-deps

COPY . .

ARG NEXT_PUBLIC_PATH=""
ENV NEXT_TELEMETRY_DISABLED=1 \
    NEXT_PUBLIC_PATH=${NEXT_PUBLIC_PATH}

RUN node --run build


# ----------- RELEASE -----------
FROM node:22-alpine AS release
WORKDIR /home/node/app

RUN apk add --no-cache libc6-compat

# Pre-instalar sharp (igual que tenías)
RUN npm i sharp@0.33.5 --prefix /tmp/sharp-pkg --progress=false --no-audit --legacy-peer-deps

COPY --chown=node:node ./public ./public
COPY --chown=node:node ./package.json ./package.json
COPY --chown=node:node ./next.config.js ./next.config.js

COPY --from=build --chown=node:node /home/node/app/.next/standalone ./
COPY --from=build --chown=node:node /home/node/app/.next/static ./.next/static

# Reemplazar sharp (igual que tenías)
RUN rm -rf ./node_modules/sharp ./node_modules/@img && \
    cp -rf /tmp/sharp-pkg/node_modules/. ./node_modules/ && \
    find /tmp/sharp-pkg/node_modules -mindepth 1 -maxdepth 1 -type d | \
      while read d; do \
        chown -R node:node "./node_modules/$(basename "$d")" 2>/dev/null || true; \
      done

ARG CI_COMMIT_SHORT_SHA
ARG CI_COMMIT_MESSAGE
ARG CI_COMMIT_REF_NAME

ENV CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA} \
    CI_COMMIT_MESSAGE=${CI_COMMIT_MESSAGE} \
    CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME}


# ----------- FINAL -----------
FROM release AS app

USER node

EXPOSE 3000

CMD ["node", "server.js"]
